### PR TITLE
Drop support for node v12

### PR DESCRIPTION
**Pull request by lo1tuma**

### CODE REVIEW

**Comment by niksy** [comment]
@lo1tuma should this be related to https://github.com/lo1tuma/eslint-plugin-mocha/issues/298#issuecomment-947417958? If Node 12 support is dropped, maybe we should release new major version?

**Comment by lo1tuma** [comment]
@niksy yes this change will be released in the next major version. I don’t think it is related to #298.

**Comment by WikiRik** [comment]
@lo1tuma can I ask why Node 12 completely was dropped? It's still in [maintenance LTS until 2022-04-30](https://nodejs.org/en/about/releases/) and eslint 8 supports `^12.22.0 || ^14.17.0 || >=16.0.0`. Wouldn't it be better to link the support to that?

**Comment by lo1tuma** [comment]
@WikiRik usually I consider to drop support for older node versions every time I’m planning to make a new major-version release. The EoL for node 12 is in only 4 months, so I think it is reasonable for people who still want to use node 12 until then to also use an older version of `eslint-plugin-mocha`.

**Comment by WikiRik** [comment]
@lo1tuma I can see that. Thanks for the quick response!

**Pull request merged**
