### PR TITLE
feat(rules): add 'valid-suite-description' rule

### LINKED ISSUE #69: Rule proposal: add "valid-suite-description" rule
Similar to the existing [valid-test-description](https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/lib/rules/valid-test-description.js) rule, but to match against the suite descriptions (`describe` or `context` or `suite`). Thanks.

### PR DESCRIPTION
**Pull request by alecxe**
Should close #69. Thanks.

### CODE REVIEW

**Comment by alecxe** [comment]
Btw, `valid-test-description` and `valid-suite-description` rules are quite similar in their implementation. To avoid code duplication we should probably refactor these rules and extract similar code chunks into reusable exported functions. I would though address after both rules are present in the codebase. What do you think? Thanks.

**Comment by lo1tuma** [comment]
Code LGTM. It seems like there are some merge conflicts. Can you rebase and resolve those conflicts?

Extracting duplicated code into re-useable libs would be very nice. I was also planning to do this for some other rules in this plugin but haven’t found time yet.

**Comment by alecxe** [comment]
Okay, fixed the conflicts. Thanks.

**Comment by lo1tuma** [comment]
Thank you.

**Pull request merged**
