### PR TITLE
Update dev dependencies

### PR DESCRIPTION
**Pull request by lo1tuma**

### CODE REVIEW

**Comment by lxanders** [comment]
Looks good to me. I'll manually merge the changes as Github seems to be unable to do it automatically.

**Comment by lo1tuma** [comment]
Manually merging is not the best idea, if you use `pr-log`. If you do that, I should also adjust the merge commit message to be in the format `Merge pull request #<pull-request-id> from <branch-name>`.

**Comment by lo1tuma** [comment]
I will fix this but I need to force push to master.

**Comment by lxanders** [comment]
Sorry for forgetting about the changelog here. Do the force push to master. Unfortunately I didn't come up with an idea how to avoid such things thinking about it.

**Comment by lo1tuma** [comment]
Done with the force push. But manually editing the merge commit messages caused an extra new line in the commit message body. `pr-log` crashes with this extra new line, see lo1tuma/pr-log#4.

**Comment by lxanders** [comment]
I merged https://github.com/lo1tuma/pr-log/pull/4 - please release a new version for `pr-log` and update (or maybe I will do it :smile:) the dependency here.

**Comment by lo1tuma** [comment]
Released pr-log 1.1.0.

**Pull request merged**
